// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: p2p_datagram.proto
// Protobuf C++ Version: 6.30.2

#include "p2p_datagram.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace gsync {

inline constexpr RespondConnectDatagram::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RespondConnectDatagram::RespondConnectDatagram(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RespondConnectDatagram_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RespondConnectDatagramDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespondConnectDatagramDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespondConnectDatagramDefaultTypeInternal() {}
  union {
    RespondConnectDatagram _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespondConnectDatagramDefaultTypeInternal _RespondConnectDatagram_default_instance_;

inline constexpr ReqConnectDatagram::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ReqConnectDatagram::ReqConnectDatagram(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ReqConnectDatagram_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReqConnectDatagramDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqConnectDatagramDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqConnectDatagramDefaultTypeInternal() {}
  union {
    ReqConnectDatagram _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqConnectDatagramDefaultTypeInternal _ReqConnectDatagram_default_instance_;
}  // namespace gsync
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_p2p_5fdatagram_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_p2p_5fdatagram_2eproto = nullptr;
const ::uint32_t
    TableStruct_p2p_5fdatagram_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::gsync::ReqConnectDatagram, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::gsync::ReqConnectDatagram, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gsync::ReqConnectDatagram, _impl_.name_),
        0,
        PROTOBUF_FIELD_OFFSET(::gsync::RespondConnectDatagram, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::gsync::RespondConnectDatagram, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gsync::RespondConnectDatagram, _impl_.name_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::gsync::ReqConnectDatagram)},
        {10, 19, -1, sizeof(::gsync::RespondConnectDatagram)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::gsync::_ReqConnectDatagram_default_instance_._instance,
    &::gsync::_RespondConnectDatagram_default_instance_._instance,
};
const char descriptor_table_protodef_p2p_5fdatagram_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022p2p_datagram.proto\022\005gsync\"\"\n\022ReqConnec"
    "tDatagram\022\014\n\004name\030\001 \001(\t\"&\n\026RespondConnec"
    "tDatagram\022\014\n\004name\030\001 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_p2p_5fdatagram_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_p2p_5fdatagram_2eproto = {
    false,
    false,
    111,
    descriptor_table_protodef_p2p_5fdatagram_2eproto,
    "p2p_datagram.proto",
    &descriptor_table_p2p_5fdatagram_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_p2p_5fdatagram_2eproto::offsets,
    file_level_enum_descriptors_p2p_5fdatagram_2eproto,
    file_level_service_descriptors_p2p_5fdatagram_2eproto,
};
namespace gsync {
// ===================================================================

class ReqConnectDatagram::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ReqConnectDatagram>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ReqConnectDatagram, _impl_._has_bits_);
};

ReqConnectDatagram::ReqConnectDatagram(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReqConnectDatagram_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gsync.ReqConnectDatagram)
}
PROTOBUF_NDEBUG_INLINE ReqConnectDatagram::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::gsync::ReqConnectDatagram& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

ReqConnectDatagram::ReqConnectDatagram(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ReqConnectDatagram& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReqConnectDatagram_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReqConnectDatagram* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:gsync.ReqConnectDatagram)
}
PROTOBUF_NDEBUG_INLINE ReqConnectDatagram::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void ReqConnectDatagram::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ReqConnectDatagram::~ReqConnectDatagram() {
  // @@protoc_insertion_point(destructor:gsync.ReqConnectDatagram)
  SharedDtor(*this);
}
inline void ReqConnectDatagram::SharedDtor(MessageLite& self) {
  ReqConnectDatagram& this_ = static_cast<ReqConnectDatagram&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ReqConnectDatagram::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReqConnectDatagram(arena);
}
constexpr auto ReqConnectDatagram::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReqConnectDatagram),
                                            alignof(ReqConnectDatagram));
}
constexpr auto ReqConnectDatagram::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReqConnectDatagram_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReqConnectDatagram::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ReqConnectDatagram>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReqConnectDatagram::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ReqConnectDatagram>(), &ReqConnectDatagram::ByteSizeLong,
              &ReqConnectDatagram::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReqConnectDatagram, _impl_._cached_size_),
          false,
      },
      &ReqConnectDatagram::kDescriptorMethods,
      &descriptor_table_p2p_5fdatagram_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ReqConnectDatagram_class_data_ =
        ReqConnectDatagram::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ReqConnectDatagram::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReqConnectDatagram_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReqConnectDatagram_class_data_.tc_table);
  return ReqConnectDatagram_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 37, 2>
ReqConnectDatagram::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReqConnectDatagram, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ReqConnectDatagram_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gsync::ReqConnectDatagram>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ReqConnectDatagram, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(ReqConnectDatagram, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\4\0\0\0\0\0\0"
    "gsync.ReqConnectDatagram"
    "name"
  }},
};
PROTOBUF_NOINLINE void ReqConnectDatagram::Clear() {
// @@protoc_insertion_point(message_clear_start:gsync.ReqConnectDatagram)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ReqConnectDatagram::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ReqConnectDatagram& this_ = static_cast<const ReqConnectDatagram&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ReqConnectDatagram::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ReqConnectDatagram& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:gsync.ReqConnectDatagram)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gsync.ReqConnectDatagram.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gsync.ReqConnectDatagram)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ReqConnectDatagram::ByteSizeLong(const MessageLite& base) {
  const ReqConnectDatagram& this_ = static_cast<const ReqConnectDatagram&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ReqConnectDatagram::ByteSizeLong() const {
  const ReqConnectDatagram& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:gsync.ReqConnectDatagram)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ReqConnectDatagram::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReqConnectDatagram*>(&to_msg);
  auto& from = static_cast<const ReqConnectDatagram&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gsync.ReqConnectDatagram)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_name().empty()) {
      _this->_internal_set_name(from._internal_name());
    } else {
      if (_this->_impl_.name_.IsDefault()) {
        _this->_internal_set_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReqConnectDatagram::CopyFrom(const ReqConnectDatagram& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gsync.ReqConnectDatagram)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReqConnectDatagram::InternalSwap(ReqConnectDatagram* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata ReqConnectDatagram::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RespondConnectDatagram::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RespondConnectDatagram>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RespondConnectDatagram, _impl_._has_bits_);
};

RespondConnectDatagram::RespondConnectDatagram(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RespondConnectDatagram_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gsync.RespondConnectDatagram)
}
PROTOBUF_NDEBUG_INLINE RespondConnectDatagram::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::gsync::RespondConnectDatagram& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

RespondConnectDatagram::RespondConnectDatagram(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RespondConnectDatagram& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RespondConnectDatagram_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RespondConnectDatagram* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:gsync.RespondConnectDatagram)
}
PROTOBUF_NDEBUG_INLINE RespondConnectDatagram::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void RespondConnectDatagram::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RespondConnectDatagram::~RespondConnectDatagram() {
  // @@protoc_insertion_point(destructor:gsync.RespondConnectDatagram)
  SharedDtor(*this);
}
inline void RespondConnectDatagram::SharedDtor(MessageLite& self) {
  RespondConnectDatagram& this_ = static_cast<RespondConnectDatagram&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RespondConnectDatagram::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RespondConnectDatagram(arena);
}
constexpr auto RespondConnectDatagram::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RespondConnectDatagram),
                                            alignof(RespondConnectDatagram));
}
constexpr auto RespondConnectDatagram::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RespondConnectDatagram_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RespondConnectDatagram::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RespondConnectDatagram>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RespondConnectDatagram::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RespondConnectDatagram>(), &RespondConnectDatagram::ByteSizeLong,
              &RespondConnectDatagram::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RespondConnectDatagram, _impl_._cached_size_),
          false,
      },
      &RespondConnectDatagram::kDescriptorMethods,
      &descriptor_table_p2p_5fdatagram_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RespondConnectDatagram_class_data_ =
        RespondConnectDatagram::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL RespondConnectDatagram::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RespondConnectDatagram_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RespondConnectDatagram_class_data_.tc_table);
  return RespondConnectDatagram_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2>
RespondConnectDatagram::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RespondConnectDatagram, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RespondConnectDatagram_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gsync::RespondConnectDatagram>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RespondConnectDatagram, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(RespondConnectDatagram, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\4\0\0\0\0\0\0"
    "gsync.RespondConnectDatagram"
    "name"
  }},
};
PROTOBUF_NOINLINE void RespondConnectDatagram::Clear() {
// @@protoc_insertion_point(message_clear_start:gsync.RespondConnectDatagram)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RespondConnectDatagram::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RespondConnectDatagram& this_ = static_cast<const RespondConnectDatagram&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RespondConnectDatagram::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RespondConnectDatagram& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:gsync.RespondConnectDatagram)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gsync.RespondConnectDatagram.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gsync.RespondConnectDatagram)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RespondConnectDatagram::ByteSizeLong(const MessageLite& base) {
  const RespondConnectDatagram& this_ = static_cast<const RespondConnectDatagram&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RespondConnectDatagram::ByteSizeLong() const {
  const RespondConnectDatagram& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:gsync.RespondConnectDatagram)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RespondConnectDatagram::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RespondConnectDatagram*>(&to_msg);
  auto& from = static_cast<const RespondConnectDatagram&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gsync.RespondConnectDatagram)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_name().empty()) {
      _this->_internal_set_name(from._internal_name());
    } else {
      if (_this->_impl_.name_.IsDefault()) {
        _this->_internal_set_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RespondConnectDatagram::CopyFrom(const RespondConnectDatagram& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gsync.RespondConnectDatagram)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RespondConnectDatagram::InternalSwap(RespondConnectDatagram* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata RespondConnectDatagram::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace gsync
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_p2p_5fdatagram_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
