if(DEFINED CMAKE_TOOLCHAIN_FILE)
    message("toolchain already set ${CMAKE_TOOLCHAIN_FILE}")
else()
    if(NOT "$ENV{VCPKG_ROOT}" STREQUAL "")
        set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE FILEPATH "Vcpkg toolchain" FORCE)
    else()
        find_program(VCPKG_EXE vcpkg)
        if(VCPKG_EXE)
            get_filename_component(VCPKG_ROOT ${VCPKG_EXE} DIRECTORY)
            set(VCPKG_TOOLCHAIN "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
            if(EXISTS ${VCPKG_TOOLCHAIN})
                set(CMAKE_TOOLCHAIN_FILE ${VCPKG_TOOLCHAIN} CACHE FILEPATH "Vcpkg toolchain" FORCE)
            endif()
        endif()
    endif()
    message("Setup vcpkg toolchain ${CMAKE_TOOLCHAIN_FILE}")
endif()